collector_pin: 23

tools:
  - id: jointer
    name: Jointer
    relay_pin: 17
    on_button_pin: 5
    off_button_pin: 6

  - id: tablesaw
    name: Table Saw
    relay_pin: 27
    on_button_pin: 13
    off_button_pin: 19

  - id: planer
    name: Planer
    relay_pin: 22
    on_button_pin: 20
    off_button_pin: 21
